name: cd

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:

  cd:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet pack --configuration Release
    
    - name: Upload to NuGet
      run: dotnet nuget push Fedandburk.Serilog.Sinks.AppCenter/bin/Release/*.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
